apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: {{ PG_FARM_SERVICE_IMAGE}}:{{APP_TAG}}
        imagePullPolicy: Always
        command: ["npm", "run", "administration"]
        env:
        - name: LOG_LEVEL
          value: "info"
        - name : "GOOGLE_APPLICATION_CREDENTIALS"
          value : "/etc/google/service-account.json"
        - name : "APP_URL"
          value : "{{APP_URL}}"
        envFrom:
        - secretRef:
            name: pg-farm-env
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
          - mountPath: /etc/google
            name: service-account
      nodeSelector:
        intendedfor: services
      volumes:
      - name: service-account
        secret:
          secretName: pg-farm-service-account