apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-gateway
spec:
  selector:
    matchLabels:
      app: dev-gateway
  template:
    metadata:
      labels:
        app: dev-gateway
    spec:
      containers:
      - name: gateway
        image: {{ PG_FARM_SERVICE_IMAGE}}:{{APP_TAG}}
        imagePullPolicy: Always
        command: ["npm", "run", "gateway"]
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: PROXY_DEBUG
          value: "true"
        - name : "GOOGLE_APPLICATION_CREDENTIALS"
          value : "/etc/google/service-account.json"
        - name : "APP_URL"
          value : "{{APP_URL}}"
        - name : "GATEWAY_HTTP_ENABLED"
          value : "true"
        - name: METRICS_ENABLED
          value: "true"
        - name: METRICS_EXPORT_GC
          value: "true"
        - name: SERVICE_NAME
          value: "dev-gateway"
        - name: PROXY_TLS_ENABLED
          value: "false"
        envFrom:
        - secretRef:
            name: app-env
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
          - mountPath: /etc/google
            name: service-account
      nodeSelector:
        intendedfor: services
      volumes:
      - name: service-account
        secret:
          secretName: service-account