apiVersion: v1
kind: Service
metadata:
  name: gateway-ingress
  annotations:
    # Use external passthrough load balancer
    # https://cloud.google.com/kubernetes-engine/docs/how-to/external-svc-lb-rbs
    # https://cloud.google.com/load-balancing/docs/passthrough-network-load-balancer
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  loadBalancerIP: "{{GKE_EXTERNAL_IP}}"
  # Use local traffic policy to preserve client source IP
  externalTrafficPolicy: Local
  selector:
    app: gateway
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https 
    protocol: TCP
    port: 443
    targetPort: 443