apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: {{ PG_FARM_SERVICE_IMAGE}}:{{APP_TAG}}
        imagePullPolicy: Always
        command: ["npm", "run", "gateway"]
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: PROXY_DEBUG
          value: "false"
        - name : "GOOGLE_APPLICATION_CREDENTIALS"
          value : "/etc/google/service-account.json"
        - name : "APP_URL"
          value : "{{APP_URL}}"
        - name : "GATEWAY_HTTP_ENABLED"
          value : "true"
        - name: METRICS_ENABLED
          value: "true"
        - name: METRICS_EXPORT_GC
          value: "true"
        - name: SERVICE_NAME
          value: "gateway"
        - name: GATEWAY_HTTPS_KEY
          value: "/etc/pgfarm/certs/pgfarm.library.ucdavis.edu/pg-farm-https-key.key"
        - name: GATEWAY_HTTPS_CERT
          value: "/etc/pgfarm/certs/pgfarm.library.ucdavis.edu/pg-farm-https-secret.cer"
        envFrom:
        - secretRef:
            name: pg-farm-env
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
          - mountPath: /etc/google
            name: service-account
          - mountPath: /etc/pgfarm/certs/pgfarm.library.ucdavis.edu
            name: pg-farm-https
      nodeSelector:
        intendedfor: services
      volumes:
      - name: service-account
        secret:
          secretName: pg-farm-service-account
      - name: pg-farm-https
        secret:
          secretName: pg-farm-https