apiVersion: v1
kind: Service
metadata:
  name: pg-proxy
spec:
  type: LoadBalancer
  loadBalancerIP: "{{GKE_EXTERNAL_IP}}"
  selector:
    app: pg-proxy
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432