apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-proxy
spec:
  selector:
    matchLabels:
      app:  pg-proxy
  template:
    metadata:
      labels:
        app:  pg-proxy
    spec:
      containers:
      - name: pg-proxy
        image: {{ PG_FARM_SERVICE_IMAGE}}:{{APP_TAG}}
        imagePullPolicy: Always
        command: ["npm", "run", "proxy"]
        env:
        - name: LOG_LEVEL
          value: "info"
        - name : "GOOGLE_APPLICATION_CREDENTIALS"
          value : "/etc/google/service-account.json"
        envFrom:
        - secretRef:
            name: pg-farm-env
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "128Mi"
            cpu: "1"
        volumeMounts:
          - mountPath: /etc/google
            name: service-account
      volumes:
      - name: service-account
        secret:
          secretName: pg-farm-service-account