apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 
spec:
  selector:
    matchLabels:
      app:  
  replicas: 1
  serviceName: 
  template:
    metadata:
      labels:
        app:
      annotations:
        gke-gcsfuse/volumes: "true"  
    spec:
      containers:
      - name: 
        image: pg
        args: ["-c", "max_connections=100"]
        imagePullPolicy: Always
        env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "password"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "500Mi"
            cpu: "0.2"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: 
          mountPath: /var/lib/postgresql/data
        - name: gcs-fuse
          mountPath: /backups
        - name: pg-socket
          mountPath: /var/run/postgresql
      - name: pg-helper
        image: 
        args: ["npm", "run", "pg-helper"]
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: LOG_LEVEL
          value: "info"
        - name : "GOOGLE_APPLICATION_CREDENTIALS"
          value : "/etc/google/service-account.json"
        # - name: METRICS_ENABLED
        #   value: "true"
        # - name: METRICS_EXPORT_GC
        #   value: "true"
        - name: SERVICE_NAME
          value: "pg-helper"
        volumeMounts:
        - name: gcs-fuse
          mountPath: /backups
        - name: pg-socket
          mountPath: /var/run/postgresql
        - name: service-account
          mountPath: /etc/google        
      serviceAccountName: pg-farm-ksa
      nodeSelector:
        intendedfor: instance-pool
      volumes:
      - name: gcs-fuse
        persistentVolumeClaim:
          claimName: gcs-fuse-pvc
      - name: pg-socket
        emptyDir: {}
      - name: service-account
        secret:
          secretName: pg-farm-service-account

  volumeClaimTemplates:
  - metadata:
      name: postgres-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi