apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app:  postgres
  replicas: 1
  serviceName: postgres
  template:
    metadata:
      labels:
        app:  postgres
    spec:
      containers:
      - name: postgres
        image: 
        args: ["-c", "max_connections=100"]
        imagePullPolicy: always
        env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "password"
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "500Mi"
            cpu: "0.25"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      nodeSelector:
        intendedfor: instance-pool

  volumeClaimTemplates:
  - metadata:
      name: postgres-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi