apiVersion: v1
kind: Service
metadata:
  name: pgfarm-instance
spec:
  # this enables direct access to the pod from within the cluster
  # and no load balancing is done
  clusterIP: None 
  selector:
    app: 
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
  - name: pg-helper
    protocol: TCP
    port: 3000