apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
spec:
  selector:
    matchLabels:
      app:  
  replicas: 1
  template:
    metadata:
      labels:
        app:  
    spec:
      containers:
      - name: pgrest
        image: 
        command: ["/services/pg-rest/run.sh"]
        imagePullPolicy: Always
        env:
        - name: PGREST_DATABASE_NAME
          value: 
        - name: PGREST_ORGANIZATION_NAME
          value: 
        resources:
          limits:
            memory: "500Mi"
            cpu: "1"
        ports:
        - containerPort: 3000
      nodeSelector:
        intendedfor: instance-pool