apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  # this enables direct access to the pod from within the cluster
  # and no load balancing is done
  clusterIP: None 
  selector:
    app: 
  ports:
  - protocol: TCP
    port: 3000