version: '3'

services:
  pg-master:
    image: postgresql:10

    volumes:
      - pg-repl-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment: 
      - PG_MASTER_HOST=${PG_MASTER_HOST}
      - PG_MASTER_PORT=${PG_MASTER_PORT}
      - PG_REP_USER=library_replicate
      - PG_REP_PASSWORD=library_replicate
    ports:
      - ${PG_FARM_MASTER_PORT}:5432

  pg-repl:
    image: streaming-replicate

    volumes:
      - pg-repl-data:/var/lib/postgresql/data
    ports:
      - ${PG_FARM_REPL_PORT}:5432
    environment: 
      - PG_MASTER_HOST=pg-master
      - PG_MASTER_PORT=5432
      - PG_REP_USER=library_replicate
      - PG_REP_PASSWORD=library_replicate

  pgr:
    image: postgrest/postgrest
    environment:
      - PGRST_DB_URI=postgres://${PGR_USER}:${PGR_PASSWORD}@pg:5432/postgres
      - PGRST_DB_SCHEMA=${PGR_SCHEMA}
      - PGRST_DB_ANON_ROLE=anon
    depends_on:
      - pg-repl
    ports:
      - ${PG_FARM_PGR_PORT}:3000

volumes:
  pg-master-data:
    driver: local
  pg-repl-data:
    driver: local